version: "3.9"

services:

  db:
    container_name: postgres_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - stack   
    env_file:
      - .env

  web:
    container_name: FastAPI_web
    depends_on:
      - migrations
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - stack
    env_file:
      - .env

  migrations:
    depends_on:
      - db
    networks:
      - stack
    build:
      context: .
    entrypoint: "alembic upgrade head"
    env_file:
      - .env


volumes:
  postgres_data:
  media:

networks:
  stack:

